const String signUpHeading = 'Create your UrbanFit account';
const String enterFullname = "Full name ";
const String enterEmail = "Email";
const String enterPhone = "Mobile";
const String enterpassword = "Password";
const String signUp = "Sign Up";
const String signUpOtp = "Sign Up with Otp";
const String signIn = "Sign In";
const String alreadyAccount = "Already have an account? ";
