List<String> workoutNames = [
  "Power Blast",
  "Cardio Fusion",
  "Bootcamp Burn",
  "Core Crusher",
  "HIIT Inferno",
  "Sculpt & Tone",
  "Tabata Thrive",
  "Strength Surge",
  "Flexibility Flow",
  "Endurance Blitz",
  "Agility Accelerator",
  "Cardio Kickstart",
  "Circuit Revamp",
  "Yoga Ignite",
  "Pump & Shred",
  "Total Body Torcher",
  "Pilates Power",
  "CrossFit Challenge",
  "Spin Sprint",
  "Functional Fitness Fire",
  "Zumba Fever",
  "Kickboxing Rampage",
  "Barre Breeze",
  "TRX Triumph",
  "Dance Fit Frenzy"
];
List<String> workoutDescriptions = [
  "An intense and explosive workout designed to boost your strength and power.",
  "A high-energy workout that combines various cardio exercises for a full-body cardiovascular challenge.",
  "A challenging workout inspired by military-style training, focusing on strength, endurance, and agility.",
  "A targeted workout aimed at strengthening and toning your core muscles, including abs and back.",
  "A high-intensity interval training (HIIT) session that pushes your limits and maximizes calorie burn.",
  "A workout focused on sculpting and toning your muscles, enhancing definition and firmness.",
  "A fast-paced workout using the Tabata protocol, featuring intense intervals of exercise and short recovery periods.",
  "A strength-focused workout designed to build muscle, increase power, and enhance overall strength.",
  "A dynamic workout that incorporates flowing movements and stretches to improve flexibility and mobility.",
  "A challenging workout aimed at improving your endurance and stamina through a mix of cardio and strength exercises.",
  "A workout that enhances agility, speed, and coordination through dynamic drills and quick movements.",
  "An energizing cardio workout that kickstarts your metabolism and boosts cardiovascular fitness.",
  "A circuit-style workout that combines different exercises to revamp your fitness routine and challenge your entire body.",
  "A dynamic yoga session that focuses on strength, balance, and flexibility, igniting your mind-body connection.",
  "A workout that combines weightlifting and high-intensity exercises to pump up your muscles and shred fat.",
  "A challenging total body workout that engages multiple muscle groups for a complete fitness experience.",
  "A workout inspired by Pilates principles, emphasizing core strength, stability, and improved posture.",
  "A high-intensity workout incorporating elements of weightlifting, cardio, and functional movements inspired by CrossFit.",
  "An indoor cycling session that simulates sprints, climbs, and intervals for an intense cardiovascular workout.",
  "A workout that focuses on functional movements to improve strength, mobility, and overall fitness.",
  "An exhilarating dance workout combining Latin rhythms and aerobic exercises to create a fun and energetic atmosphere.",
  "A high-energy kickboxing workout that combines punches, kicks, and cardio drills for a full-body challenge.",
  "A workout that blends ballet-inspired movements, Pilates, and yoga to tone muscles, improve posture, and increase flexibility.",
  "A workout that utilizes TRX suspension training to build strength, stability, and flexibility using bodyweight exercises.",
  "A dynamic and fun dance fitness session that gets your heart pumping and body moving to the beat."
];

List<String> workoutUrl = [
  'https://www.freepik.com/free-photo/people-working-out-indoors-together-with-dumbbells_20287182.htm#query=workout&position=7&from_view=search&track=sph',
  'https://www.freepik.com/free-photo/young-woman-doing-fitness-sportswear_19116591.htm#query=workout&position=8&from_view=search&track=sph',
  'https://www.freepik.com/free-photo/stronger-young-muscular-caucasian-athlete-practicing-lunges-gym-with-barbell-male-model-doing-strength-exercises-training-his-lower-body-wellness-healthy-lifestyle-bodybuilding-concept_15075304.htm#query=workout&position=19&from_view=search&track=sph',
  'https://www.freepik.com/free-photo/woman-enjoying-running-sport_27640380.htm#query=workout&position=23&from_view=search&track=sph',
  'https://www.freepik.com/free-photo/full-shot-people-barre-group-class_40956463.htm#query=workout&position=6&from_view=search&track=sph'
];
